---
title: "Graph_DC"
author: "Alan Thomas Joshy"
date: "2024-05-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Load all packages necessary
```{r}
library(dplyr)
library(ggplot2)
```

We load the data into the rmd file:

```{r}
library(readr)


Bull_data <- read_csv("../data/Plot_Deco/Bull_shark_data.csv")
View(Bull_data)

hammerhead_data <- read_csv("../data/Plot_Deco/hammerhead_data.csv")
View(hammerhead_data)

Tiger_data <- read_csv("../data/Plot_Deco/Tiger_shark_data.csv")
View(Tiger_data)
```
we now need to combine the data for the different species into one data frame and so we will add a column called species to distinguish the data for the different shark species.

```{r}
Bull_data <- Bull_data |> mutate(Species = "Bull Shark")

hammerhead_data <- hammerhead_data |> mutate(Species = "Hammerhead Shark")

Tiger_data <- Tiger_data|> mutate(Species = "Tiger Shark")


#Combine data frames:
Com_dta <- bind_rows(Bull_data, hammerhead_data, Tiger_data)
Com_dta
```



TO make a plot

```{r}
plt <- ggplot2::ggplot(data = Com_dta, aes(x = Year, y = No., colour = Species, group = Species)) +
  geom_line() +
  theme_light() +
  labs(title = "Capture numbers by the Queensland Shark Capture Program from 1997 to 2013", x = "Year", y = "No. of Sharks captured") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

plt

```


